export const PAGE_HEADER_NAVBAR_HEIGHT = 68;

export const PAGE_HEADER_LICENSE_TIP_HEIGHT = 44;

export const DEFAULT_PAGE_HEADER_HEIGHT = PAGE_HEADER_NAVBAR_HEIGHT;

export const PAGE_HEADER_HEIGHT_WITH_LICENSE_TIP =
  PAGE_HEADER_NAVBAR_HEIGHT + PAGE_HEADER_LICENSE_TIP_HEIGHT;
