/*
 * This file is part of KubeSphere Console.
 * Copyright (C) 2019 The KubeSphere Console Authors.
 *
 * KubeSphere Console is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KubeSphere Console is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with KubeSphere Console.  If not, see <https://www.gnu.org/licenses/>.
 */

module.exports = {
  abortPipeline: 'abortPipeline',
  'Absolute duration': 'Absolute duration',
  ADD_ACTION: 'Add Action',
  'Add another credential': 'Add another credential',
  'Add conditions': 'Add conditions',
  'Add nesting conditions': 'Add nesting conditions',
  'Add nesting steps': 'Add nesting steps',
  'Add Parallel Stage': 'Add Parallel Stage',
  'Add Step': 'Add Step',
  ALL_BRANCHES: 'Include all branches',
  CHOICE_PARAM_OPTION_DESC:
    'Enter an option in each line. The first line is used as the default option.',
  CODE_REPOSITORY_ADDRESS_DESC: 'Use a repository that contains a Jenkinsfile.',
  CODE_REPOSITORY_ADDRESS_EMPTY_TIP:
    'Please enter the address of a code repository.',
  archiveArtifacts: 'archiveArtifacts',
  'Are you sure to close this pipeline Editor ?':
    'Are you sure to close this pipeline Editor ?',
  CLOSE_JENKINSFILE_EDITOR_TIP: 'Are you sure to close the Jenkinsfile editor?',
  artifacts: 'artifacts',
  ARTIFACT_PL: 'Artifacts',
  'Authentication Token': 'Authentication Token',
  'Automatically generated by GitHub': 'Automatically generated by GitHub',
  bcc: 'bcc',
  BEHAVIORAL_STRATEGY: 'Behavioral Strategy',
  blocker: 'blocker',
  BLOCKER: 'Blocker',
  CRITICAL: 'Critical',
  MAJOR: 'Major',
  MINOR: 'Minor',
  NOTICE: 'Notice',
  BRANCH_SI: 'Branch',
  BRANCH_PL: 'Branches',
  CODE_REPOSITORY_BRANCH: 'Code Repository Branch',
  Branches: 'Branches',
  BRANCH_COUNT: 'Branches',
  BRANCH_EXCLUDED: 'Excluded Branches',
  BRANCH_INCLUDED: 'Included Branches',
  'branch success': 'branch success',
  BRANCH_SETTINGS: 'Branch Settings',
  BREAK: 'Break',
  BUILD_SETTINGS: 'Build Settings',
  BUILD_TRIGGER: 'Build Trigger',
  '@somebody to help review': '@somebody to help review',
  'Send messages by email': 'Send messages by email',
  'Send messages in the build': 'Send messages in the build',
  CANCELLED_IN_REVIEW: 'Cancelled in review',
  CC: 'CC',
  'Change Current Directory': 'Change Current Directory',
  'Chinese is not allowed in the pipeline configuration':
    'Chinese is not allowed in the pipeline configuration',
  'Clean when aborted': 'Clean when aborted',
  'Clean Workspace': 'Clean Workspace',
  CLONE_DEPTH: 'Clone Depth',
  CODE_CHECK: 'Code Check',
  'Code Quality Check': 'Code Quality Check',
  CODE_REPOSITORY: 'Code Repository',
  VULNERABILITY_PL: 'Vulnerabilities',
  CODE_SMELL_PL: 'Code Smells',
  PARAMETER_DESCRIPTION_DESC: 'Set the parameter description.',
  COMMIT_PL: 'Commits',
  COMMIT: 'Commit',
  COMMIT_ID: 'Commit ID',
  'Config File Path': 'Config File Path',
  'config name': 'config name',
  configs: 'configs',
  'Configuration error': 'Configuration error',
  container: 'container',
  Continue: 'Continue',
  COVERAGE: 'Coverage',
  CREATE_CREDENTIAL: 'Create Credential',
  CREATE_PIPELINE: 'Create Pipeline',
  CREDENTIAL_SI: 'Credential',
  'credential Id': 'credential Id',
  'Credential Id': 'Credential Id',
  CREDENTIAL_NAME: 'Credential Name',
  SCAN_REPO_SUCCESS: 'Repository scan was triggered successfully.',
  CREDENTIAL_PL: 'Credentials',
  CREDENTIAL: 'Credential',
  CREDENTIAL_LOW: 'credential',
  CREDENTIALS_MANAGEMENT: 'Credential Management',
  credentialsId: 'credentialsId',
  critical: 'critical',
  'Current branch name must match the input value':
    'Current branch name must match the input value',
  BUILD_RECORD_RETENTION_PERIOD_DAYS: 'Build Record Retention Period (days)',
  BRANCH_RETENTION_PERIOD_DAYS: 'Branch Retention Period (days)',
  'defaultValue -1 means not to discard':
    'defaultValue -1 means not to discard',
  'Delete all resources of the deployment file':
    'Delete all resources of the deployment file',
  'Deploy resources to the Kubernetes cluster':
    'Deploy resources to the Kubernetes cluster',
  "Didn't pass": "Didn't pass",
  dir: 'dir',
  Discard: 'Discard',
  DELETE_OUTDATED_BRANCHES: 'Delete outdated branches',
  DELETE_OUTDATED_BUILD_RECORDS: 'Delete outdated build records',
  DISCOVER_TAG_BRANCHES: 'Discover Tags',
  DISCOVER_BRANCHES: 'Discover Branches',
  'Discover branches from repository': 'Discover branches from repository',
  DISCOVER_PR_FROM_FORKS: 'Discover PRs from Forks',
  DISCOVER_PR_FROM_ORIGIN: 'Discover PRs from Origin',
  'Discover pull requests from forks': 'Discover pull requests from forks',
  'Discover pull requests from origin': 'Discover pull requests from origin',
  DISPLAY_ALL: 'Display All',
  ENABLE_TAG_BRANCH_DISCOVERY: 'Enable tag discovery',
  DISABLE_TAG_BRANCH_DISCOVERY: 'Disable tag discovery',
  'Docker Container Registry Credentials':
    'Docker Container Registry Credentials',
  'Docker Registry URL': 'Docker Registry URL',
  dockerCredentials: 'dockerCredentials',
  DOWNLOAD_LOGS: 'Download Logs',
  'Drag and drop tasks to sort': 'Drag and drop tasks to sort',
  Duration: 'Duration',
  DURATION: 'Duration',
  DURATION_VALUE: 'Duration: {value}',
  echo: 'echo',
  'Edit Config': 'Edit Config',
  'Edit Credential': 'Edit Credential',
  EDIT_JENKINSFILE: 'Edit Jenkinsfile',
  EDIT_PIPELINE: 'Edit Pipeline',
  'Enable Variable Substitution in Config':
    'Enable Variable Substitution in Config',
  enableConfigSubstitution: 'enableConfigSubstitution',
  'Enter an expression': 'Enter an expression',
  'Environment name': 'Environment name',
  EXCLUDE_PR_BRANCHES: 'Exclude branches filed as PRs',
  'Executes the code inside the block with a determined time out limit.':
    'Executes the code inside the block with a determined time out limit.',
  expression: 'expression',
  Failure: 'Failure',
  'For accessing GitHub': 'For accessing GitHub',
  USERS_WITH_PERMISSION: 'Users with the admin or write permission',
  'get token': 'get token',
  CLONE_SETTINGS: 'Clone Settings',
  SCAN_PERIODICALLY: 'Scan periodically',
  NO_CONCURRENT_BUILD_DESC:
    'Set the the pipeline to run only one build task at a time.',
  info: 'info',
  input: 'input',
  'Inspection results do not affect subsequent tasks':
    'Inspection results do not affect subsequent tasks',
  'instance failed to match at least one schema':
    'instance failed to match at least one schema',
  'Internal nested conditions only need to satisfy one':
    'Internal nested conditions only need to satisfy one',
  'Internal nesting conditions must be matched':
    'Internal nesting conditions must be matched',
  ISSUE_PL: 'Issues',
  PIPELINE_PARAM_DEFAULT_DESC:
    'Set the default value of the parameter. You can change the value before manually running the pipeline.',
  'Jenkinsfile syntax error, message': 'Jenkinsfile syntax error, message',
  'key File Variable': 'key File Variable',
  keyFileVariable: 'keyFileVariable',
  'Kubeconfig Variable': 'Kubeconfig Variable',
  'Kubernetes Namespace for Secret': 'Kubernetes Namespace for Secret',
  'Kubernetes Secrets': 'Kubernetes Secrets',
  LAST_MESSAGE: 'Last Message',
  LAST_MESSAGE_SCAP: 'Last message',
  Line: 'Line',
  LINE_VALUE: 'Line: {value}',
  CODE_LINE_COUNT: 'Code Lines',
  'Load credentials into environment variables':
    'Load credentials into environment variables',
  'Load the sonarqube configuration provided by Jenkins into the Pipeline.':
    'Load the sonarqube configuration provided by Jenkins into the Pipeline.',
  mail: 'mail',
  major: 'major',
  MAXIMUM_BRANCHES: 'Maximum Branches',
  MAXIMUM_BUILD_RECORDS: 'Maximum Build Records',
  minor: 'minor',
  "Missing one or more required properties: 'name'":
    "Missing one or more required properties: 'name'",
  'Negative prefix': 'Negative prefix',
  NO_ARTIFACT_FOUND_TIP: 'No artifact is found.',
  NO_BRANCH_FOUND_TIP: 'No branch is found.',
  NO_COMMIT_FOUND: 'No Commit Found',
  NO_CONCURRENT_BUILDS: 'No concurrent builds',
  'No need': 'No need',
  NO_STATUS: 'No status',
  Normal: 'Normal',
  'Not Build': 'Not Build',
  'Not fail build': 'Not fail build',
  NOT_RUNNING: 'Not running',
  NOT_BUILT: 'Not built',
  'not support edit nested stage': 'not support edit nested stage',
  BUILD_RECORD_RETENTION_PERIOD_DAYS_DESC:
    'Build records that exceed the retention period are deleted. The default value is 7.',
  MAXIMUM_BUILD_RECORDS_DESC:
    'When the number of build records exceeds the maximum number allowed, the earliest build record is deleted. The default value is 10.',
  ONLY_PR_BRANCHES: 'Include only branches filed as PRs',
  BUILD_PARAMETERS: 'Build Parameters',
  SET_PARAMETERS: 'Set Parameters',
  PASSPHRASE: 'Passphrase',
  'passphrase Variable': 'passphrase Variable',
  passphraseVariable: 'passphraseVariable',
  'Password Variable': 'Password Variable',
  passwordVariable: 'passwordVariable',
  PIPELINE: 'Pipeline',
  PIPELINE_PL: 'Pipelines',
  PIPELINE_LOW: 'pipeline',
  CLONE_TIMEOUT_PERIOD: 'Clone Timeout Period (min)',
  NO_PIPELINE_CONFIG_FILE_TIP: 'No pipeline configuration file is found.',
  'Pipeline Configuration': 'Pipeline Configuration',
  PIPELINE_EVENT_TRIGGER: 'Trigger through pipeline events',
  INITIALIZING_PIPELINE: 'Pipeline Initializing',
  INITIALIZING_PIPELINE_DESC:
    'Please wait until the pipeline initialization is complete.',
  'Pipeline List': 'Pipeline List',
  PIPELINE_RUN_LOGS: 'Pipeline Run Logs',
  'pipeline syntax error': 'pipeline syntax error',
  'Please add at least one step.': 'Please add at least one step.',
  'Please input images name': 'Please input images name',
  PIPELINE_NAME_TIP: 'Please enter a pipeline name.',
  'Please input the credential name.': 'Please input the credential name.',
  SELECT_CODE_REPO_DESC: 'Select a code repository to be used by the pipeline.',
  'Press enter for the next': 'Press enter for the next',
  'Print message': 'Print message',
  PRIVATE_KEY: 'Private Key',
  PROCEED: 'Proceed',
  'Pull code by Git': 'Pull code by Git',
  'Pull code by SVN': 'Pull code by SVN',
  PULL_STRATEGY: 'Pull Strategy',
  WEBHOOK_PUSH_URL: 'Webhook Push URL',
  Queue: 'Queue',
  QUEUED: 'Queued',
  ABORTED: 'Aborted',
  UNSTABLE: 'Unstable',
  Recipient: 'Recipient',
  REGEX: 'Regular Expression',
  'Registry Credentials': 'Registry Credentials',
  remote: 'remote',
  REMOTE_REPOSITORY_URL: 'Remote Repository URL',
  CODE_REPOSITORY_ADDRESS: 'Code Repository URL',
  REPOSITORY_NAME: 'Code Repository',
  REPOSITORY_NAME_EMPTY_TIP: 'Please enter the name of a code repository.',
  RESCAN: 'Rescan',
  RUN: 'Run',
  RUN_ID: 'Run ID',
  'Run Pipeline': 'Run Pipeline',
  'Save Artifact': 'Save Artifact',
  SCAN_INTERVAL: 'Scan Interval',
  LOGS_OBTAINED_SUCCESSFULLY: 'The logs were obtained successfully.',
  'Repo Scanned Successfully': 'Repo Scanned Successfully',
  SCAN_TRIGGER: 'Scan Trigger',
  REPOSITORY_SCAN_LOGS: 'Repository Scan Logs',
  SCAN_REPOSITORY: 'Scan Repository',
  VIEW_SCAN_LOGS: 'View Scan Logs',
  BUILD_PERIODICALLY: 'Build periodically',
  SCM: 'SCM',
  SCRIPT_PATH: 'Script Path',
  WEBHOOK_PUSH: 'Webhook Push',
  secretName: 'secretName',
  secretNamespace: 'secretNamespace',
  SELECT_PIPELINE_SCAP: 'Select pipeline',
  SELECT_CODE_REPOSITORY: 'Select Code Repository',
  SELECT_THIS_REPOSITORY: 'Select This Repository',
  Sender: 'Sender',
  sh: 'sh',
  'Shell commands can be executed in the container':
    'Shell commands can be executed in the container',
  'Show Advanced Settings': 'Show Advanced Settings',
  VIEW_LOGS: 'View Logs',
  DISPLAY_ONLY_LAST_TEN: 'Only the last 10 issues are displayed.',
  'show yaml editor': 'show yaml editor',
  SINGLE_SVN: 'Single-branch SVN',
  SVN: 'SVN',
  SKIPPED: 'Skipped',
  'sonar is the default config name.': 'sonar is the default config name.',
  "Sorry, you don't have the permission to do this.":
    "Sorry, you don't have the permission to do this.",
  'Specify a container to add nested tasks to execute inside the container':
    'Specify a container to add nested tasks to execute inside the container',
  SCRIPT_PATH_DESC: 'Set the path of the Jenkinsfile in the code repository.',
  'Start the follow-up task after the inspection':
    'Start the follow-up task after the inspection',
  'Started By': 'Started By',
  STOP_PIPELINE_SUCCESS: 'The pipeline was stopped successfully.',
  SUB_HEALTHY: 'Sub-healthy',
  Subject: 'Subject',
  submitter: 'submitter',
  submitterParameter: 'submitterParameter',
  TASK_FAILED_NOT_OPERATIONAL: 'The stage has failed and is not operational.',
  TASK_STATUS: 'Task Status',
  TEST_RESULTS: 'Results',
  'Text Variable': 'Text Variable',
  'The conditions required to implement the current phase (optional).':
    'The conditions required to implement the current phase (optional).',
  KUBECONFIG_CONTENT_DESC:
    'The default content is the kubeconfig settings of the current user.',
  'The environment variable entered before running the pipeline is match the current value.':
    'The environment variable entered before running the pipeline is match the current value.',
  'The label on which to run the Pipeline or individual stage':
    'The label on which to run the Pipeline or individual stage',
  PIPELINE_NAME_DESC:
    'The name of the pipeline. Pipelines in the same project must have different names.',
  'This name has been used.': 'This name has been used.',
  'Time Used': 'Time Used',
  Timeout: 'Timeout',
  TIMEOUT_VALUE: 'Timeout: {value}',
  timeout: 'timeout',
  'Timeout after no activity in logs for this block':
    'Timeout after no activity in logs for this block',
  timer: 'timer',
  PASSWORD_TOKEN: 'Password/Token',
  TRIGGER_REMOTE_BUILD: 'Trigger a remote build (for example, using a script)',
  TRUSTED_USERS: 'Trusted User',
  Unnamed: 'Unnamed',
  BITBUCKET_ADDRESS_EMPTY_TIP:
    'Please enter the address of a Bitbucket server.',
  BITBUCKET_ADDRESS_INVALID_TIP: 'Invalid Bitbucket server address.',
  'Use the following URL to remotely triggerworkbench the build':
    'Use the following URL to remotely triggerworkbench the build',
  'User types that can trigger builds': 'User types that can trigger builds',
  'username or group name, multiple values ​​used, separated':
    'username or group name, multiple values ​​used, separated',
  'Username Variable': 'Username Variable',
  usernameVariable: 'usernameVariable',
  WAITING_FOR_INPUT: 'Waiting for input...',
  waitForQualityGate: 'waitForQualityGate',
  HEALTH: 'Health',
  Webhook: 'Webhook',
  WHEN_CREATE_PIPELINE: 'Trigger on Pipeline Creation',
  WHEN_DELETE_PIPELINE: 'Trigger on Pipeline Deletion',
  ENABLE_SHALLOW_CLONE: 'Enable shallow clone',
  withCredentials: 'withCredentials',
  withSonarQubeEnv: 'withSonarQubeEnv',
  'Wrong Token': 'Wrong Token',
  'You can execute shell commands or windows batch commands in the build.':
    'You can execute shell commands or windows batch commands in the build.',

  PIPELINE_DESC: `A pipeline is an extensible set of tools that can be combined
    to achieve continuous integration and continuous delivery.
    You can create and manage pipelines on this page.`,
  username_password: 'Username and password',
  CREDENTIAL_TYPE_USERNAME_PASSWORD: 'Username and password',
  CREDENTIAL_TYPE_SSH: 'SSH key',
  CREDENTIAL_TYPE_SECRET_TEXT: 'Access token',
  CREDENTIAL_TYPE_KUBECONFIG: 'kubeconfig',
  login_Plateform: 'Login platform',
  CREDENTIALS_DESC: `Credentials are objects that contain some sensitive data,
    such as username and password, SSH key and Token.
    They are used to provide authentication for pulling code,
    pushing/pulling images, executing SSH scripts, etc. when a pipeline is running.`,
  BUILD_PARAMETERS_TIP: 'Pass build parameters to the pipeline.',
  AUTHENTICATION_TOKEN_TIP: `Enable this option if you need to
    trigger a build by accessing a predefined URL.
    A typical use of this feature is to trigger through the source code
    management system's hook script.
    You need to provide an authorization token in the form of a string so that
    only the person with the authorization token can trigger the remote build.`,
  DELETE_OUTDATED_BUILD_RECORDS_TIP: `Set the system to automatically delete outdated build records including console output, archived artifacts, and metadata to save disk space.`,
  DELETE_OUTDATED_BRANCHES_TIP:
    'Set the system to automatically delete outdated branches to save disk space.',
  BUILD_PERIODICALLY_TIP: 'Set the pipeline to periodically run build tasks.',
  BRANCH_RETENTION_PERIOD_DAYS_DESC:
    'Branches that exceed the retention period are deleted. The default value is 7.',
  MAXIMUM_BRANCHES_DESC:
    'When the number of branches exceeds the maximum number allowed, the earliest branch is deleted. The default value is 5.',
  CRON_TIP: `This field follows the cron syntax (slightly different).
    Specifically, each line contains 5 fields separated by tabs or spaces.
    minutes: the first few minutes of an hour (0-59)
    hours: the first few hours of the day (0-23)
    the days of the month: the first few days of a month (1-31 )
    Month: The first few days of the first few days (0-12), the first few days of the week (0-12),
    0 and 7 are Sundays. `,

  PIPELINES_BASEINFO_DESC:
    'Please enter the basic information of the pipeline.',
  PIPELINE_ADVANCE_SETTINGS_DESC:
    'Configure a complex behavior policy for the pipeline (Optional).',
  CREDENTIALS_CREATE_DESC: 'Create credentials for DevOps projects',
  CHECKOUT_DESC: 'Pull code; often used to pull non-git code, such as svn.',
  PRIVATE_IMAGE_DESC: `To deploy from a private image repository,
    you need to create a mirrored repository and then pull the image. `,
  AGENT_TYPE_DESC: `The agent section specifies
    where the entire Pipeline or a particular stage will be executed in the Jenkins environment,
    depending on where the Agent part is placed.
    This part must be defined at the top level within the pipeline block,
    but the stage level usage is optional. `,
  AUTHENTICATION_TOKEN_DESC: `Use the following URL to remotely trigger the build:
    JENKINS_URL / job / JOB_NAME / build? Token =TOKEN_NAME or /buildWithParameters?
    Token = TOKEN_NAME You can choose to append &cause=reason to provide the text that
    will be included in the build reason for the record. `,
  ACTIVITY_EMPTY_TIP: 'The pipeline has not been run.',

  PIPELINE_NO_CONFIG:
    'The relevant configuration file was not found in the current pipeline',
  INVALID_JENKINSFILE_TIP:
    'The current Jenkinsfile is not a standard declarative Jenkinsfile and graphical display is unavailable.',
  PIPELINE_SCHEDULE_DESC:
    'Enter a CRON expression to set a schedule. <a href="//jenkins.io/doc/book/pipeline/syntax/#cron-syntax" target="_blank">Learn More</a>',
  WEBHOOK_PUSH_DESC:
    'Push a message to this URL to trigger a scan of the repository. ',
  WEBHOOK_DESC: 'Configure webhook notifications by setting a webhook server.',
  TIME_TRIGGER_DESC: 'Scan the code repository periodically.',

  KUBERNETES_DEPLOY_DESC: `Deploy resources on a Kubernetes cluster.
    In a continuous integration or continuous deployment environment,
    only those resources that need to be updated regularly should be placed in the deployment step.
    Therefore, this step is mostly used to process the deployment of such resources.`,
  KUBERNETES_DEPLOY_DESC_MORE: `<br />
  <label>This step has the following main features:</label>
  <li>Distribution without kubectl</li>
  <li>Variable substitution in Jenkinsfile, Dynamic deployment is possible. </li>
  <li>Support for pulling docker images from private image repositories</li>
  <label> Currently this step supports the following resources:</label>
  <br />
  <li>Configuration </li>
  <li>Key</li>
  <li>Deploy</li>
  <li>Dave Process Set</li>
  <li>App Routing</li>
  <li>Namespace</li>
  <li>Task</li>
  <li>Service</li>
  <li>Replica Set</li>
  <li>
  Replication
  Controller (rolling updates are not supported, and use Deployment if you want to use rolling updates)
  </li>`,

  OPTIONS_PR_PARAMS_1: 'Pull the code with the PR merged',
  OPTIONS_PR_PARAMS_2: 'Pull the code at the point of the PR',
  OPTIONS_PR_PARAMS_3: 'Create two pipelines respectively',

  SELECT_CREDENTIAL_DESC:
    'Select a credential used to access a code repository.',
  PIPELINE_PREPARE_DESC: 'Preparing the environment...',
  PARAMS_DESC: `The following parameters are generated based on the pipeline settings or
     the parameters section of the Jenkinsfile, which are entered according to operational requirements.`,
  EDIT_CREDENTIAL_DESC:
    'The following form will not display the original credential information. The original information will be overwritten by any new input.',
  pipeline_conditions: 'Conditions',
  PARAMS_STRING: 'String',
  PARAMS_TEXT: 'Multi-line string',
  PARAMS_BOOLEAN: 'Boolean',
  PARAMS_CHOICE: 'Options',
  PARAMS_PASSWORD: 'Password',
  PARAMS_TEXT_TCAP: 'Multi-line String',
  CODE_SMELL: 'Code Smell',
  BUG: 'Bug',
  BUG_PL: 'Bugs',
  VULNERABILITY: 'Vulnerability',
  SECURITY_HOTSPOT: 'Security Hotspot',
  FILTER_BY_REGEX: 'Filter by Regex',
  FILTER_BY_REGEX_DESC:
    'Use a regular expression to filter branches, PRs, and tags',
  waitForQualityGate_desc:
    "Code quality check standards are derived from SonarQube's Quality Gate. If you need to customize the standards, go to SonarQube settings.",
  PIPELINE_CREATE_DESC:
    "Pipeline's task execution will begin after the initialization is complete.",
  REVIEW_DESC:
    'When the pipeline runs here, this task will be suspended, and you can choose to continue or terminate after the review.',
  INPUT_DESC:
    'When the pipeline runs here, the task will be suspended, and the creator and @somebody can choose to continue or terminate the pipeline.',
  INPUT_MESSAGE_DESC:
    'This message will be displayed in the pipeline running state.',

  withSonarQubeEnv_DESC:
    'Quickly locate potential or obvious errors in your code',
  waitForQualityGate_DESC: 'Executed after performing code analysis',
  script_DESC: 'Execute groovy script',
  PIPELINE_QUEUED_TITLE: 'About to Complete Initialization',
  PIPELINE_QUEUED_DESC:
    'You need to wait for the agent to start and execute the pipeline (note that if the agent has not started for a long time, please check the agent configuration and cluster resources).',
  pipeline_owner:
    'The owner of the DevOps project, with the highest authorization of the project, can perform all operations',
  pipeline_maintainer:
    'The maintainer of the DevOps project can perform credentials and pipeline configuration in the DevOps project',
  pipeline_developer:
    'The developer of the DevOps project can trigger and view the pipeline',
  pipeline_reporter:
    'The Observer of the DevOps project can only view the resources of the project',
  LoadPrevData_Desc:
    'It was detected that this pipeline was not successfully edited last time. Is the last data loaded to continue editing?',
  PATTERN_PIPELINE_NAME_VALID_NAME_TIP:
    "Invalid name (Support uppercase and lowercase letters, numbers, '_' and '-')",
  INCORRECT_GITHUB_TOKEN_DESC: `Incorrect GitHub token.
  <a
    class="float-right"
    href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
    target="_blank"
  >
    Obtain GitHub Token
  </a>`,
  GET_GITHUB_TOKEN_DESC: `For accessing GitHub
  <a
    class="float-right"
    href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
    target="_blank"
  >
    Get Token
  </a>`,

  BITBUCKET_SERVER_CREDENTIAL_EMPTY:
    'Please set a Bitbucket server and credential.',
  GITHUB_CREDENTIAL_EMPTY: 'Please set a GitHub credential.',
  PIPELINES_FOOTER_SEE_MORE: 'Go to the branch details page to see more.',
  PIPELINE_CRON_DESC: 'The pipeline will be run at {nextTime} next time.',
  JENKINS_LINS_ERROR: 'has syntax error at line {line}.',
  WHEN_DELETE_PIPELINE_DESC:
    'When a pipeline is deleted, the tasks in the specified pipeline are automatically triggered.',
  WHEN_CREATE_PIPELINE_DESC:
    'When a new pipeline is created, the tasks in the specified pipeline are automatically triggered.',
  STARTED_BY_NAME: 'Started By: {name}',
  CREDENTIAL_NAME_EXIST_DESC:
    'The credential name already exists. Please enter another name.',
  'Invalid credential ID': 'Invalid credential ID',
  CI: 'Continuous Integration (CI)',
  CI_DESC:
    'Continuous integration (CI) is the process of automatically detecting, pulling, building, and (in most cases) unit testing after source code changes.',
  CICD: 'Continuous Integration & Delivery (CI/CD)',
  CICD_DESC:
    "Continuous deployment (CD) refers to the idea of automatically providing the release version in the continuous delivery pipeline to end users. According to the user's installation method, automatic deployment in the cloud environment, app upgrades (such as apps on mobile phones), website updates, or only the list of available versions.",
  CUSTOM_PIPELIEN: 'Custom Pipeline',
  CUSTOM_PIPELIEN_DESC:
    'You can select the tasks you need to customize the contents of the pipeline.',
  COPY_PIPELINE: 'Copy Pipeline',
  PIPELINE_RUN_START_SI: 'Starts to run the pipeline...',
  PIPELINE_RUN_START_PL: 'Starts to run the pipelines...',
  BATCH_RUN_SUCCESS_SI: 'The pipeline was run successfully.',
  BATCH_RUN_SUCCESS_PL: 'The pipelines were run successfully.',
  'Batch Run Fail': 'Batch Run Failed',
  'Run Start': 'Start Running',
  GITLAB_SERVER_ADDRESS: 'GitLab Server Address',
  GITLAB_SERVER_EMPTY_TIP: 'Please enter the address of a GitLab server.',
  PROJECT_GROUP_OWNER: 'Project Group/Owner',
  PROJECT_GROUP_OWNER_EMPTY_TIP:
    'Please enter the name of a GitLab project group or project owner.',
  BITBUCKET_SERVER_ADDRESS: 'Bitbucket Server Address',
  BITBUCKET_SERVER_EMPTY_TIP: 'Please enter the address of a Bitbucket server.',
  CREATE_PIPELINE_DESC: 'Build, test and deploy with Pipelines',
  'Choose a Pipeline Template': 'Choose a Pipeline Template',
  BATCH_RUN_UNSUPPORTED_DESC: 'Multi-branch pipelines cannot run in a batch.',
  SYNC_STATUS: 'Sync Status',

  // Pipeline List Page
  PULL_REQUEST_PL: 'Pull Requests',
  PULL_REQUEST_COUNT: 'Pull Requests',
  HEALTHY: 'Healthy',

  // Pipeline Creation Page
  DEVOPS_PROJECT_DESC:
    'DevOps projects are used to group resources and control the resource management permissions of different users.',
  PIPELINE_CREATE_DEVOPS_PROJECT_DESC:
    'Select the DevOps project to which the pipeline belongs.',
  CODE_REPOSITORY_OPTIONAL: 'Code Repository (optional)',
  OPTIONS: 'Options',
}
