/*
 * This file is part of KubeSphere Console.
 * Copyright (C) 2019 The KubeSphere Console Authors.
 *
 * KubeSphere Console is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KubeSphere Console is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with KubeSphere Console.  If not, see <https://www.gnu.org/licenses/>.
 */

module.exports = {
  abortPipeline: 'abortPipeline',
  'Absolute duration': 'Absolute duration',
  'Add Action': 'Add Action',
  'Add another credential': 'Add another credential',
  'Add conditions': 'Add conditions',
  'Add nesting conditions': 'Add nesting conditions',
  'Add nesting steps': 'Add nesting steps',
  'Add Parallel Stage': 'Add Parallel Stage',
  'Add Step': 'Add Step',
  'All branches': 'All branches',
  'Alternate options, one per line. The first line will be used as the default option.':
    'Alternate options, one per line. The first line will be used as the default option.',
  'Any repository containing Jenkinsfile will be built automatically.':
    'Any repository containing Jenkinsfile will be built automatically.',
  archiveArtifacts: 'archiveArtifacts',
  'Are you sure to close this pipeline Editor ?':
    'Are you sure to close this pipeline Editor ?',
  'Are you sure to close this jenkinsfile Editor ?':
    'Are you sure to close this jenkinsfile Editor ?',
  artifacts: 'artifacts',
  Artifacts: 'Artifacts',
  'Authentication Token': 'Authentication Token',
  'Automatically generated by GitHub': 'Automatically generated by GitHub',
  bcc: 'bcc',
  'Behavioral strategy': 'Behavioral strategy',
  blocker: 'blocker',
  Branch: 'Branch',
  Branches: 'Branches',
  'Branch Count': 'Branch Count',
  'Branch Excluded': 'Branch Excluded',
  'Branch Included': 'Branch Included',
  'branch success': 'branch success',
  'Branch Settings': 'Branch Settings',
  Break: 'Break',
  'Build Settings': 'Build Settings',
  'Build Trigger': 'Build Trigger',
  '@somebody to help review': '@somebody to help review',
  'Send messages by email': 'Send messages by email',
  'Send messages in the build': 'Send messages in the build',
  'Cancelled in review': 'Cancelled in review',
  CC: 'CC',
  'Change Current Directory': 'Change Current Directory',
  'Chinese is not allowed in the pipeline configuration':
    'Chinese is not allowed in the pipeline configuration',
  'Clean when aborted': 'Clean when aborted',
  'Clean Workspace': 'Clean Workspace',
  'clone depth': 'clone depth',
  'Code Quality': 'Code Quality',
  'Code Quality Check': 'Code Quality Check',
  'Code Repository': 'Code Repository',
  'Code Vulnerability': 'Code Vulnerability',
  CodeSmells: 'CodeSmells',
  'Comment information': 'Comment information',
  Commit: 'Commit',
  commit: 'commit',
  'Config File Path': 'Config File Path',
  'config name': 'config name',
  configs: 'configs',
  'Configuration error': 'Configuration error',
  container: 'container',
  Continue: 'Continue',
  Coverage: 'Coverage',
  'Create a credential': 'Create a credential',
  'Create Credentials': 'Create Credentials',
  'Create Pipeline': 'Create Pipeline',
  Credential: 'Credential',
  'credential Id': 'credential Id',
  'Credential Id': 'Credential Id',
  'Credential ID': 'Credential ID',
  Credentials: 'Credentials',
  'Credentials Management': 'Credentials Management',
  credentialsId: 'credentialsId',
  critical: 'critical',
  'Current branch name must match the input value':
    'Current branch name must match the input value',
  'Days to keep builds': 'Days to keep builds',
  'Days to keep old branches': 'Days to keep old branches',
  'defaultValue -1 means not to discard':
    'defaultValue -1 means not to discard',
  'Delete all resources of the deployment file':
    'Delete all resources of the deployment file',
  'Deploy resources to the Kubernetes cluster':
    'Deploy resources to the Kubernetes cluster',
  "Didn't pass": "Didn't pass",
  dir: 'dir',
  Discard: 'Discard',
  'Discard old branch': 'Discard old branch',
  'Discard old builds': 'Discard old builds',
  'Discover Tag Branches': 'Discover Tag Branches',
  'Discover Branches': 'Discover Branches',
  'Discover branches from repoitory': 'Discover branches from repoitory',
  'Discover PR from Forks': 'Discover PR from Forks',
  'Discover PR from Origin': 'Discover PR from Origin',
  'Discover pull requests from forks': 'Discover pull requests from forks',
  'Discover pull requests from origin': 'Discover pull requests from origin',
  'Display All': 'Display All',
  'Enable Discover Tag Branches': 'Enable discovery of Tag branch',
  'Disable Discover Tag Branches': 'Disable the discovery of the Tag branch',
  'Docker Container Registry Credentials':
    'Docker Container Registry Credentials',
  'Docker Registry URL': 'Docker Registry URL',
  dockerCredentials: 'dockerCredentials',
  'Download Logs': 'Download Logs',
  'Drag and drop tasks to sort': 'Drag and drop tasks to sort',
  Duration: 'Duration',
  echo: 'echo',
  'Edit Config': 'Edit Config',
  'Edit Credential': 'Edit Credential',
  'Edit Jenkinsfile': 'Edit Jenkinsfile',
  'Edit Pipeline': 'Edit Pipeline',
  'Enable Variable Substitution in Config':
    'Enable Variable Substitution in Config',
  enableConfigSubstitution: 'enableConfigSubstitution',
  'Enter an expression': 'Enter an expression',
  'Enviroment name': 'Enviroment name',
  'Exclude branches that are also filed as PRs':
    'Exclude branches that are also filed as PRs',
  'Executes the code inside the block with a determined time out limit.':
    'Executes the code inside the block with a determined time out limit.',
  expression: 'expression',
  Failure: 'Failure',
  'For accessing GitHub': 'For accessing GitHub',
  'From users with Admin or Write permission':
    'From users with Admin or Write permission',
  'get token': 'get token',
  'Git Clone Options': 'Git Clone Options',
  'If not, scan regularly': 'If not, scan regularly',
  'If you check this option, you cannot run multiple builds concurrently.':
    'If you check this option, you cannot run multiple builds concurrently.',
  info: 'info',
  input: 'input',
  'Inspection results do not affect subsequent tasks':
    'Inspection results do not affect subsequent tasks',
  'instance failed to match at least one schema':
    'instance failed to match at least one schema',
  'Internal nested conditions only need to satisfy one':
    'Internal nested conditions only need to satisfy one',
  'Internal nesting conditions must be matched':
    'Internal nesting conditions must be matched',
  Issues: 'Issues',
  'It specifies the default value of the field, allowing the user to save the typed actual value.':
    'It specifies the default value of the field, allowing the user to save the typed actual value.',
  'Jenkinsfile syntax error, message': 'Jenkinsfile syntax error, message',
  'key File Variable': 'key File Variable',
  keyFileVariable: 'keyFileVariable',
  'Kubeconfig Variable': 'Kubeconfig Variable',
  'Kubernetes Namespace for Secret': 'Kubernetes Namespace for Secret',
  'Kubernetes Secrets': 'Kubernetes Secrets',
  'Last Message': 'Last Message',
  Line: 'Line',
  'Line number': 'Line number',
  'Lines of Code': 'Lines of Code',
  'Load credentials into environment variables':
    'Load credentials into environment variables',
  'Load the sonarqube configuration provided by Jenkins into the Pipeline.':
    'Load the sonarqube configuration provided by Jenkins into the Pipeline.',
  mail: 'mail',
  major: 'major',
  'Max number of branches to keep': 'Max number of branches to keep',
  'Maximum number of builds to keep': 'Maximum number of builds to keep',
  minor: 'minor',
  "Missing one or more required properties: 'name'":
    "Missing one or more required properties: 'name'",
  'Negative prefix': 'Negative prefix',
  'No artifacts records': 'No artifacts records',
  'No branches found': 'No branches found',
  'No commit records': 'No commit records',
  'No concurrent builds': 'No concurrent builds',
  'No need': 'No need',
  'no status': 'no status',
  Normal: 'Normal',
  'Not Build': 'Not Build',
  'Not fail build': 'Not fail build',
  'not run': 'not run',
  'not support edit nested stage': 'not support edit nested stage',
  'Old builds will be deleted after this number of days.':
    'Old builds will be deleted after this number of days.',
  'Old builds will be discarded after the build number exceeds the maximum amount.':
    'Old builds will be discarded after the build number exceeds the maximum amount.',
  'Only branches that are also filed as PRs':
    'Only branches that are also filed as PRs',
  'Parametric Build': 'Parametric Build',
  'Params Input': 'Params Input',
  passphrase: 'passphrase',
  'passphrase Variable': 'passphrase Variable',
  passphraseVariable: 'passphraseVariable',
  'Password Variable': 'Password Variable',
  passwordVariable: 'passwordVariable',
  Pipeline: 'Pipeline',
  'Pipeline clone timeout (in minutes)': 'Pipeline clone timeout (in minutes)',
  'Pipeline config file not found': 'Pipeline config file not found',
  'Pipeline Configuration': 'Pipeline Configuration',
  'Pipeline event trigger': 'Pipeline event trigger',
  'Pipeline initialization': 'Pipeline initialization',
  'Pipeline List': 'Pipeline List',
  'Pipeline Run Logs': 'Pipeline Run Logs',
  'pipeline syntax error': 'pipeline syntax error',
  Pipelines: 'Pipelines',
  'Please add at least one step.': 'Please add at least one step.',
  'Please input images name': 'Please input images name',
  'Please input pipeline name': 'Please input pipeline name',
  'Please input the credential name.': 'Please input the credential name.',
  'Please select a code repository as the code source for the pipeline.':
    'Please select a code repository as the code source for the pipeline.',
  'Press enter for the next': 'Press enter for the next',
  'Print message': 'Print message',
  'Private key': 'Private key',
  Proceed: 'Proceed',
  'Pull code by Git': 'Pull code by Git',
  'Pull code by SVN': 'Pull code by SVN',
  'Pull Strategy': 'Pull Strategy',
  'Push message to': 'Push message to',
  Queue: 'Queue',
  Queued: 'Queued',
  Recipient: 'Recipient',
  'Regex filter': 'Regex filter',
  'Registry Credentials': 'Registry Credentials',
  remote: 'remote',
  'Remote Repository URL': 'Remote Repository URL',
  'Repository Url': 'Repository URL',
  'Repository Name': 'Repository Name',
  Rescan: 'Rescan',
  Review: 'Review',
  Run: 'Run',
  'Run Pipeline': 'Run Pipeline',
  'Save Artifact': 'Save Artifact',
  'Scan interval': 'Scan interval',
  'Logs Scanned Successfully': 'Logs Scanned Successfully',
  'Repo Scanned Successfully': 'Repo Scanned Successfully',
  'Scan Repo Trigger': 'Scan Repo Trigger',
  'Scan Reponsitory Logs': 'Scan Reponsitory Logs',
  'Scan Repository': 'Scan Repository',
  Schedule: 'Schedule',
  'Scheduled build': 'Scheduled build',
  SCM: 'SCM',
  'Script Path': 'Script Path',
  'Secret Name': 'Secret Name',
  secretName: 'secretName',
  secretNamespace: 'secretNamespace',
  'select a pipeline': 'select a pipeline',
  'Select Code Repository': 'Select Code Repository',
  'Select This Repository': 'Select This Repository',
  Sender: 'Sender',
  sh: 'sh',
  'Shell commands can be executed in the container':
    'Shell commands can be executed in the container',
  'Show Advanced Settings': 'Show Advanced Settings',
  'Show Logs': 'Show Logs',
  'Show only the last 10': 'Show only the last 10',
  'show yaml editor': 'show yaml editor',
  'single Svn': 'single Svn',
  Skipped: 'Skipped',
  'sonar is the default config name.': 'sonar is the default config name.',
  "Sorry, you don't have the permission to do this.":
    "Sorry, you don't have the permission to do this.",
  'Specify a container to add nested tasks to execute inside the container':
    'Specify a container to add nested tasks to execute inside the container',
  'Specify the location of the Jenkinsfile in the source code repository':
    'Specify the location of the Jenkinsfile in the source code repository',
  'Start the follow-up task after the inspection':
    'Start the follow-up task after the inspection',
  'Started By': 'Started By',
  'Stop Job Successfully, Status updated later':
    'Stop Job Successfully, Status updated later',
  'Sub-healthy': 'Sub-healthy',
  Subject: 'Subject',
  submitter: 'submitter',
  submitterParameter: 'submitterParameter',
  'Task failed, not operational': 'Task failed, not operational',
  TaskStatus: 'TaskStatus',
  'Test Result': 'Test Result',
  'Text Variable': 'Text Variable',
  'The conditions required to implement the current phase (optional).':
    'The conditions required to implement the current phase (optional).',
  "The default value here is the current user's kubeconfig.":
    "The default value here is the current user's kubeconfig.",
  'The environment variable entered before running the pipeline is match the current value.':
    'The environment variable entered before running the pipeline is match the current value.',
  'The label on which to run the Pipeline or individual stage':
    'The label on which to run the Pipeline or individual stage',
  'The name of the pipeline. Pipelines in the same project must have different names.':
    'The name of the pipeline. Pipelines in the same project must have different names.',
  'This name has been used.': 'This name has been used.',
  'This name has existed.': 'This name has existed.',
  'Time Used': 'Time Used',
  Timeout: 'Timeout',
  timeout: 'timeout',
  'Timeout after no activity in logs for this block':
    'Timeout after no activity in logs for this block',
  timer: 'timer',
  'Token / Password': 'Token / Password',
  'Trigger a remote build (for example, using a script)':
    'Trigger a remote build (for example, using a script)',
  'Trusted User': 'Trusted User',
  Unnamed: 'Unnamed',
  'url is invalid': 'url is invalid',
  'Use the following URL to remotely triggerworkbench the build':
    'Use the following URL to remotely triggerworkbench the build',
  'User types that can trigger builds': 'User types that can trigger builds',
  'username or group name, multiple values ​​used, separated':
    'username or group name, multiple values ​​used, separated',
  'Username Variable': 'Username Variable',
  usernameVariable: 'usernameVariable',
  'Wait for interactive input': 'Wait for interactive input',
  waitForQualityGate: 'waitForQualityGate',
  WeatherScore: 'WeatherScore',
  Webhook: 'Webhook',
  'When Create Pipeline': 'When Create Pipeline',
  'When Delete Pipeline': 'When Delete Pipeline',
  'Whether to enable shallow clone': 'Whether to enable shallow clone',
  withCredentials: 'withCredentials',
  withSonarQubeEnv: 'withSonarQubeEnv',
  'Wrong Token': 'Wrong Token',
  'You can execute shell commands or windows batch commands in the build.':
    'You can execute shell commands or windows batch commands in the build.',

  PIPELINE_DESC: `A pipeline is a collection of plugins that can be combined
    to achieve continuous integration and continuous delivery.
    Pipeline DSL provides us with an extensible set of tools that allow
    us to implement simple to complex logic through code.`,
  username_password: 'Account Credentials',
  login_Plateform: 'Login platform',
  CREDENTIALS_DESC: `Credentials are objects that contain some sensitive data,
    such as username and password, SSH key and Token.
    They are used to provide authentication for pulling code,
    pushing/pulling images, executing SSH scripts, etc. when a pipeline is running.`,
  tips_Parametric_build: `The parameterized build process allows
    you to pass in one or more parameters when you build.
    For example: You may have a pipeline for publishing software and you
    want to upload the release notes together.
    This can be done by adding text parameters here.
    Each parameter has a Name and a Value,
    and the value of Value depends on the parameter type.
    These values can be accessed in the Pipeline using params.Name or Name.
    This means that each parameter defined here should have a unique name.
    When parameterizing a project, the build is replaced with a parameterized build,
    which prompts the user to enter a value for each defined parameter.
    If they choose not to enter anything,
    the build proceeds with the default value for each parameter.
    If the project's build is started automatically, for example, by a timed trigger,
    it will be triggered with the default value of the parameter. `,
  tips_Authentication_token: `Enable this option if you need to
    trigger a build by accessing a predefined URL.
    A typical use of this feature is to trigger through the source code
    management system's hook script.
    You need to provide an authorization token in the form of a string so that
    only the person with the authorization token can trigger the remote build.`,
  tips_disable_concurrent: `This will determine when the
    project's build record should be discarded.
    Build records include console output, archive artifacts,
    and other metadata related to a particular build.
    Keeping less builds saves disk space used by Jenkins.
    We provide two conditions to determine when the old build should be discarded:
    1. Number of days to keep the build:
    The build will be discarded after a certain number of days.
    2. Number of builds to be kept:
    If there are already a certain number of builds, discard the oldest build.
    These two conditions apply to the build at the same time,
    and if either one is met first, the build will be discarded.`,
  tips_disable_concurrent_withscm: `This will determine when the branch should be discarded and all build records under the branch.
    The build record includes the console output,
    Archive artifacts and other metadata related to a particular build.
    Keeping less builds saves disk space used by Jenkins.
    We provide two options to determine when the old branch should be discarded:
    1. Number of days to keep the branch: If the branch reaches a certain number of days,
    the branch is dropped.
    2. Number of reserved branches: If a certain number of branches already exist,
    the oldest branch is discarded.
    These two options can work on the branch at the same time.
    If any of the limits are exceeded,
    any branches that exceed this limit will be dropped.`,
  tips_Timing_build:
    'Provides cron-like functionality to perform this project regularly',
  tips_days_keep_withscm: `If the number of days the branch has been retained will be deleted.
    (Default -1: will delete the branch that has been deleted)`,
  tips_numbers_keep_withscm: `If the number of branches reached the number of reservations will be deleted.
    (Default value -1: will delete the branches that have been deleted)`,
  tips_timer_trigger: `This field follows the cron syntax (slightly different).
    Specifically, each line contains 5 fields separated by tabs or spaces.
    minutes: the first few minutes of an hour (0-59)
    hours: the first few hours of the day (0-23)
    the days of the month: the first few days of a month (1-31 )
    Month: The first few days of the first few days (0-12), the first few days of the week (0-12),
    0 and 7 are Sundays. `,

  PIPELINES_BASEINFO_DESC:
    'Please enter the basic information of the pipeline.',
  PIPELINE_ADVANCE_SETTINGS_DESC:
    'Configure a complex behavior policy for the pipeline (Optional).',
  CREDENTIALS_CREATE_DESC: 'Create credentials for DevOps projects',
  CHECKOUT_DESC: 'Pull code; often used to pull non-git code, such as svn.',
  PRIVATE_IMAGE_DESC: `To deploy from a private image repository,
    you need to create a mirrored repository and then pull the image. `,
  AGENT_TYPE_DESC: `The agent section specifies
    where the entire Pipeline or a particular stage will be executed in the Jenkins environment,
    depending on where the Agent part is placed.
    This part must be defined at the top level within the pipeline block,
    but the stage level usage is optional. `,
  AUTHENTICATION_TOKEN_DESC: `Use the following URL to remotely trigger the build:
    JENKINS_URL / job / JOB_NAME / build? Token =TOKEN_NAME or /buildWithParameters?
    Token = TOKEN_NAME You can choose to append &cause=reason to provide the text that
    will be included in the build reason for the record. `,
  ACTIVITY_EMPTY_TIP: 'The current pipeline is not running yet',

  PIPELINE_NO_CONFIG:
    'The relevant configuration file was not found in the current pipeline',
  NOT_VALID_JENKINS_FILE: `The current Jenkinsfile is not a standard declarative Jenkinsfile
    and cannot be graphically displayed`,
  PIPELINE_CRONJOB_CRON_DESC: `Every hour, on the hour syntax reference
    <a href="//jenkins.io/doc/book/pipeline/syntax/#cron-syntax" target="_blank">CRON</a>`,
  WEBHOOK_DESC:
    'Push a message to this URL to trigger a reindexing of the repository. ',
  TIME_TRIGGER_DESC: `Some types of items will automatically re-index
    when they receive an external push message.
    However, in some cases, message notifications may fail.
    This option will check if the index has been executed within the specified time interval,
    and if not, trigger the index. `,

  KUBERNETES_DEPLOY_DESC: `Deploy resources on a Kubernetes cluster.
    In a continuous integration or continuous deployment environment,
    only those resources that need to be updated regularly should be placed in the deployment step.
    Therefore, this step is mostly used to process the deployment of such resources.`,
  KUBERNETES_DEPLOY_DESC_MORE: `<br />
  <label>This step has the following main features:</label>
  <li>Distribution without kubectl</li>
  <li>Variable substitution in Jenkinsfile, Dynamic deployment is possible. </li>
  <li>Support for pulling docker images from private image repositories</li>
  <label> Currently this step supports the following resources:</label>
  <br />
  <li>Configuration </li>
  <li>Key</li>
  <li>Deploy</li>
  <li>Dave Process Set</li>
  <li>App Routing</li>
  <li>Namespace</li>
  <li>Task</li>
  <li>Service</li>
  <li>Replica Set</li>
  <li>
  Replication
  Controller (rolling updates are not supported, and use Deployment if you want to use rolling updates)
  </li>`,

  OPTIONS_PR_PARAMS_1: 'Source code version of PR merged with target branch',
  OPTIONS_PR_PARAMS_2: 'Source code version of PR itself',
  OPTIONS_PR_PARAMS_3: `Two pipelines are created when PR is discovered.
    A pipeline uses the source code version of PR itself,
    A pipelined version of the source code merged with the target branch using PR`,

  ADD_NEW_CREDENTIAL_DESC:
    'Obtaining repository code may require credentials. Please select an existing credential or add a new one.',
  PIPELINE_PREPAIR_DESC:
    'The environment is being prepared. There will be a graphical display later.',
  PARAMS_DESC: `The following parameters are generated based on the pipeline settings or
     the parameters section of the Jenkinsfile, which are entered according to operational requirements.`,
  EDIT_CREDENTIAL_DESC:
    'The following form will not display the original credential information. Re-entering it will overwrite it.',
  pipeline_conditions: 'Conditions',
  PARAMS_STRING: 'String',
  PARAMS_TEXT: 'Text',
  PRARMS_BOOLEAN: 'Boolean',
  PARAMS_CHOICE: 'Choice',
  PARAMS_PASSWORD: 'Password',
  CODE_SMELL: 'Code Smell',
  BUG: 'Bug',
  VULNERABILITY: 'Vulnerability',
  SECURITY_HOTSPOT: 'Security Hotspot',
  REG_FILTER_DESC:
    'Enable regular expressions, ignoring names that do not match the provided regular expression (including branches and PRs)',
  waitForQualityGate_desc:
    "Code quality check standards are derived from SonarQube's Quality Gate. If you need to customize the standards, go to SonarQube settings.",
  PIPELINE_CREATE_DESC:
    "Pipeline's task execution will begin after the initialization is complete.",
  REVIEW_DESC:
    'When the pipeline runs here, this task will be suspended, and you can choose to continue or terminate after the review.',
  INPUT_DESC:
    'When the pipeline runs here, the task will be suspended, and the creator and @somebody can choose to continue or terminate the pipeline.',
  INPUT_MESSAGE_DESC:
    'This message will be displayed in the pipeline running state.',

  withSonarQubeEnv_DESC:
    'Quickly locate potential or obvious errors in your code',
  waitForQualityGate_DESC: 'Executed after performing code analysis',
  script_DESC: 'Execute groovy script',
  PIPELINE_QUEUED_TITLE: 'Pipeline will be initialized soon',
  PIPELINE_QUEUED_DESC:
    'You need to wait for the agent to start and execute the pipeline (note that if the agent has not started for a long time, please check the agent configuration and cluster resources).',
  pipeline_owner:
    'The owner of the DevOps project, with the highest authorization of the project, can perform all operations',
  pipeline_maintainer:
    'The maintainer of the DevOps project can perform credentials and pipeline configuration in the DevOps project',
  pipeline_developer:
    'The developer of the DevOps project can trigger and view the pipeline',
  pipeline_reporter:
    'The Observer of the DevOps project can only view the resources of the project',
  LoadPrevData_Desc:
    'It was detected that this pipeline was not successfully edited last time. Is the last data loaded to continue editing?',
  PATTERN_PIPELINE_NAME_VALID_NAME_TIP:
    "Invalid name (Support uppercase and lowercase letters, numbers, '_' and '-')",
  WRONG_GITHUB_TOKEN_DESC: `Wrong Token
  <a
    class="float-right"
    href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
    target="_blank"
  >
    Get Token
  </a>`,
  GET_GITHUB_TOKEN_DESC: `For accessing GitHub
  <a
    class="float-right"
    href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
    target="_blank"
  >
    Get Token
  </a>`,

  bitbucket_server_ACCESSTOKEN_PLACEHOLDER:
    'Please input your Bitbucket account information.',
  github_ACCESSTOKEN_PLACEHOLDER: 'Please input your GitHub access token.',
  PIPELINES_FOOTER_SEE_MORE: 'Go to the branch details page to see more.',
  CRON_DESC: 'Would last have run at {lastTime}; would next run at {nextTime}',
  JENKINS_LINS_ERROR: 'has syntax error at line {line}.',
  WHEN_DELETE_PIEPLINE_DESC:
    'When a pipeline is deleted, the tasks in the specified pipeline are automatically triggered.',
  WHEN_CHRETE_PIEPLINE_DESC:
    'When a new pipeline is created, the tasks in the specified pipeline are automatically triggered.',
  'Started By {name}': 'Started By {name}',
  'Credential ID exists': 'Credential ID exists',
  'Invalid credential ID': 'Invalid credential ID',
  CI: 'Continuous Integration (CI)',
  CI_DESC:
    'Continuous integration (CI) is the process of automatically detecting, pulling, building, and (in most cases) unit testing after source code changes.',
  CICD: 'Continuous Integration & Delivery (CI/CD)',
  CICD_DESC:
    "Continuous deployment (CD) refers to the idea of automatically providing the release version in the continuous delivery pipeline to end users. According to the user's installation method, automatic deployment in the cloud environment, app upgrades (such as apps on mobile phones), website updates, or only the list of available versions.",
  CUSTOM_PIPELIEN: 'Custom Pipeline',
  CUSTOM_PIPELIEN_DESC:
    'You can select the tasks you need to customize the contents of the pipeline.',
  'Copy Pipeline': 'Copy Pipeline',
  'Batch Run Start': 'Batch Run Start',
  'Batch Run Success': 'Batch Run Completed',
  'Batch Run Fail': 'Batch Run Failed',
  'Run Start': 'Start Running',
  'GitLab Server': 'GitLab Server',
  'GitLab Owner': 'Owner',
  CREATE_PIPELINE_DESC: 'Build, test and deploy with Pipelines',
  'Choose a Pipeline Template': 'Choose a Pipeline Template',
  BATCH_RUN_DESC: 'Multi-branch does not support batch operation',
  'Sync Status': 'Sync Status',
}
