/*
 * This file is part of KubeSphere Console.
 * Copyright (C) 2019 The KubeSphere Console Authors.
 *
 * KubeSphere Console is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KubeSphere Console is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with KubeSphere Console.  If not, see <https://www.gnu.org/licenses/>.
 */

module.exports = {
  abortPipeline: 'abortPipeline',
  'Absolute duration': 'Duración total',
  ADD_ACTION: 'Agregar acción',
  'Add another credential': 'Agregar otra credencial',
  'Add conditions': 'Agregar condiciones',
  'Add nesting conditions': 'Agregar condiciones anidadas',
  'Add nesting steps': 'Agregar pasos anidados',
  'Add Parallel Stage': 'Agregar pasos paralelos',
  'Add Step': 'Agregar paso',
  ALL_BRANCHES: 'Todas las ramas',
  CHOICE_PARAM_OPTION_DESC:
    'Enter one option per each line. La primera línea se usará como la opción predeterminada.',
  GIT_REPO_DESC: 'Use a repository that contains Jenkinsfiles.',
  archiveArtifacts: 'archiveArtifacts',
  'Are you sure to close this pipeline Editor ?':
    '¿Estás seguro de cerrar este editor de pipeline?',
  CLOSE_JENKINSFILE_EDITOR_TIP:
    '¿Estás seguro de cerrar este editor de jenkinsfile?',
  artifacts: 'artefactos',
  Artifacts: 'Artefactos',
  'Authentication Token': 'Token de autenticación',
  'Automatically generated by GitHub': 'Generado automáticamente por GitHub',
  bcc: 'bcc',
  BEHAVIORAL_STRATEGY: 'Estrategia de comportamiento',
  blocker: 'bloqueador',
  CODE_REPOSITORY_BRANCH: 'Rama',
  Branches: 'Ramas',
  BRANCH_COUNT: 'Número de rama',
  BRANCH_EXCLUDED: 'Rama excluida',
  BRANCH_INCLUDED: 'Rama incluida',
  'branch success': 'Rama correcta',
  BRANCH_SETTINGS: 'Configuración de ramas',
  Break: 'Rotura',
  BUILD_SETTINGS: 'Configuración de compilación',
  BUILD_TRIGGER: 'Crear disparador',
  '@somebody to help review': '¿Puede @alguien ayudar a revisar esto?',
  'Send messages by email': 'Puedes enviar mensajes por correo electrónico.',
  'Send messages in the build': 'Puedes enviar mensajes en la compilación',
  'Cancelled in review': 'Cancelado en la revisión',
  CC: 'CC',
  'Change Current Directory': 'Cambiar directorio actual',
  'Chinese is not allowed in the pipeline configuration':
    'El chino no está permitido en la configuración de la pipeline',
  'Clean when aborted': 'Limpiar cuando aborte',
  'Clean Workspace': 'Limpiar entono de trabajo',
  CLONE_DEPTH: 'profundidad de clonado',
  'Code Quality': 'Código de calidad',
  'Code Quality Check': 'Código de control de calidad',
  CODE_REPOSITORY: 'Repositorio de Código',
  'Code Vulnerability': 'Vulnerabilidad de código',
  CodeSmells: 'CodeSmells',
  PARAM_DESC: 'Descripción del parámetro.',
  Commit: 'Commit',
  commit: 'commit',
  'Config File Path': 'Ruta del archivo de configuración',
  'config name': 'nombre de configuración',
  configs: 'configs',
  'Configuration error': 'Error de configuración',
  container: 'contenedor',
  Continue: 'Seguir',
  Coverage: 'Cobertura',
  CREATE_A_CREDENTIAL: 'Crear una credencial',
  CREATE_CREDENTIAL: 'Crear credenciale',
  CREATE_PIPELINE: 'Crear pipeline',
  CREDENTIAL_SI: 'Autentificación',
  'credential Id': 'ID de autentificación',
  'Credential Id': 'ID de autentificación',
  CREDENTIAL_ID: 'ID de autentificación',
  CREDENTIAL_PL: 'Autentificación',
  CREDENTIAL: 'Credential',
  CREDENTIAL_LOW: 'credential',
  CREDENTIALS_MANAGEMENT: 'Gestión de credenciales',
  credentialsId: 'credenciales',
  critical: 'crítico',
  'Current branch name must match the input value':
    'El nombre de la rama actual debe coincidir con el valor de entrada',
  DAYS_TO_KEEP_BUILDS: 'Días para mantener las build',
  DAYS_TO_KEEP_BRANCHES: 'Días para mantener ramas',
  'defaultValue -1 means not to discard':
    'defaultValue -1 significa no descartar',
  'Delete all resources of the deployment file':
    'Eliminar todos los recursos del archivo de despliegue',
  'Deploy resources to the Kubernetes cluster':
    'Implementar recursos en el clúster de Kubernetes',
  "Didn't pass": 'No pasó',
  dir: 'directorio',
  Discard: 'Descarte',
  DISCARD_OLD_BRANCHES: 'Descartar ramas anteriores',
  DISCARD_OLD_BUILDS: 'Descartar builds antiguas',
  'Discover Tag Branches': 'Descubrir Tag ramas',
  'Discover Branches': 'Descubrir ramas',
  'Discover branches from repository': 'Descubrir ramas desde el repositorio',
  'Discover PR from Forks': 'Descubrir PR desde Forks',
  'Discover PR from Origin': 'Descubrir PR desde Origin',
  'Discover pull requests from forks': 'Descubrir las PR desde forks',
  'Discover pull requests from origin': 'Descubrir las PR desde origin',
  'Display All': 'Mostrar todo',
  ENABLE_TAG_BRANCH_DISCOVERY: 'Habilitar descoberta de ramo de tag',
  DISABLE_TAG_BRANCH_DISCOVERY: 'Desativar a descoberta do ramo tag',
  'Docker Container Registry Credentials':
    'credenciales de Docker Container Registry',
  'Docker Registry URL': 'URL del Docker Registry',
  dockerCredentials: 'dockerCredentials',
  DOWNLOAD_LOGS: 'Descargar Logs',
  'Drag and drop tasks to sort': 'Arrastra y suelta tareas para ordenar',
  Duration: 'Duración',
  echo: 'echo',
  'Edit Config': 'Editar la configuración',
  'Edit Credential': 'Editar credenciales',
  'Edit Jenkinsfile': 'Editar Jenkinsfile',
  EDIT_PIPELINE: 'Editar pipeline',
  'Enable Variable Substitution in Config':
    'Habilitar la sustitución de variables en la configuración',
  enableConfigSubstitution: 'enableConfigSubstitution',
  'Enter an expression': 'Introdir una expresión',
  'Environment name': 'Nombre del entorno',
  EXCLUDE_PR_BRANCHES: 'Excluir las ramas que también se presentan como PRs',
  'Executes the code inside the block with a determined time out limit.':
    'Ejecuta el código dentro del bloque con un límite de tiempo determinado.',
  expression: 'expresión',
  Failure: 'Fallo',
  'For accessing GitHub': 'Para acceder a GitHub',
  USERS_WITH_PERMISSION:
    'De usuarios con permiso de administrador o de escritura',
  'get token': 'obtener token',
  GIT_CLONE_OPTIONS: 'Opciones de clonación de Git',
  SCAN_REGULARLY: 'Scan regularly if not otherwise triggered',
  NO_CONCURRENT_BUILD_DESC:
    'Si marca esta opción, no podrá ejecutar varias compilaciones simultáneamente.',
  info: 'informacion',
  input: 'entrada',
  'Inspection results do not affect subsequent tasks':
    'Los resultados de la inspección no afectan las tareas posteriores.',
  'instance failed to match at least one schema':
    'la instancia no ha modido compararse con al menos un esquema',
  'Internal nested conditions only need to satisfy one':
    'Las condiciones anidadas solo necesitan cumplir una condición',
  'Internal nesting conditions must be matched':
    'Las condiciones internas de anidación deben coincidir',
  Issues: 'Problemas',
  PIPELINE_PARAM_DEFAULT_DESC:
    'The default value of the field. You can also change the default value before manually running a pipeline.',
  'Jenkinsfile syntax error, message':
    'Error de sintaxis de Jenkinsfile, mensaje',
  'key File Variable': 'variable de archivo clave',
  keyFileVariable: 'keyFileVariable',
  'Kubeconfig Variable': 'Variable de Kubeconfig',
  'Kubernetes Namespace for Secret': 'Namespace de Kubernetes para el Secret',
  'Kubernetes Secrets': 'Secrets de Kubernetes',
  LAST_MESSAGE: 'Ultimo mensaje',
  LAST_MESSAGE_SCAP: 'Last message',
  Line: 'Línea',
  'Line number': 'Número de línea',
  'Lines of Code': 'Líneas de código',
  'Load credentials into environment variables':
    'Cargue credenciales en variables de entorno',
  'Load the sonarqube configuration provided by Jenkins into the Pipeline.':
    'Cargue la configuración de sonarqube proporcionada por Jenkins en la Pipeline.',
  mail: 'correo',
  major: 'mayor',
  MAXIMUM_NUMBER_OF_BRANCHES_TO_KEEP:
    'Número máximo de ramas viejas a mantener',
  MAXIMUM_NUMBER_OF_BUILDS_TO_KEEP:
    'Número máximo de compilaciones para mantener',
  minor: 'menor',
  "Missing one or more required properties: 'name'":
    "Falta una o más propiedades requeridas: 'nombre'",
  'Negative prefix': 'Prefijo negativo',
  'No artifacts records': 'No hay registro de artefactos.',
  'No branches found': 'No se encontraron ramas',
  'No commit records': 'Sin registros de commits',
  NO_CONCURRENT_BUILDS: 'No hay builds concurrentes',
  'No need': 'No necesario',
  NO_STATUS: 'sin Estado',
  Normal: 'Normal',
  'Not Build': 'Sin Build',
  'Not fail build': 'Build no fallida',
  'not run': 'no ejecutar',
  'not support edit nested stage': 'no admite editar en la fase anidada',
  DAYS_TO_KEEP_BUILDS_DESC:
    'Old builds are discarded after this number of days. The default value is 7.',
  MAXIMUM_NUMBER_OF_BUILDS_TO_KEEP_DESC:
    'Old builds are discarded when the build number exceeds the maximum number. The default value is 10.',
  ONLY_PR_BRANCHES: 'Solo las ramas que también se presentan como PR',
  PARAMETERIZED_BUILD: 'Build parametrizado',
  ENTER_PARAMETERS: 'Entrada de parámetros',
  PASSPHRASE: 'Pasphrase',
  'passphrase Variable': 'Variable de passphrase',
  passphraseVariable: 'passphraseVariable',
  'Password Variable': 'Variable de contraseña',
  passwordVariable: 'Variable de contraseña',
  PIPELINE: 'Pipeline',
  PIPELINE_PL: 'Pipelines',
  PIPELINE_LOW: 'pipeline',
  PIPELINE_CLONE_TIMEOUT:
    'Tiempo de espera de clonación de pipeline agotado (en minutos)',
  'Pipeline config file not found':
    'Archivo de configuración de Pipeline no encontrado',
  'Pipeline Configuration': 'Configuración de Pipeline',
  PIPELINE_EVENT_TRIGGER: 'Disparador de eventos de Pipelines',
  'Pipeline initialization': 'Inicialización de Pipeline',
  'Pipeline List': 'Lista de Pipelines',
  'Pipeline Run Logs': 'Registros de ejecución de Pipelines',
  'pipeline syntax error': 'error de sintaxis en la Pipeline',
  'Please add at least one step.': 'Por favor agregue al menos un paso.',
  'Please input images name': 'Por favor introduce el nombre de las imágenes',
  PIPELINE_NAME_TIP: 'Por favor introduce el nombre de la pipeline',
  'Please input the credential name.':
    'Por favor introduce el nombre de la credencial.',
  SELECT_CODE_REPO_DESC:
    'Selecciona un repositorio de código como fuente de código para la pipeline.',
  'Press enter for the next': 'Presione enter para ir al siguiente paso',
  'Print message': 'Imprimir mensaje',
  PRIVATE_KEY: 'Llave privada',
  Proceed: 'Continuar',
  'Pull code by Git': 'Pull código con Git',
  'Pull code by SVN': 'Pull código con SVN',
  PULL_STRATEGY: 'Estrategia de Pull',
  WEBHOOK_PUSH_URL: 'Webhook Push URL',
  Queue: 'Cola',
  Queued: 'Encolado',
  Recipient: 'Recipiente',
  REGEX_FILTER: 'Filtro de expresiones regulares',
  'Registry Credentials': 'Credenciales de registro',
  remote: 'remoto',
  REMOTE_REPOSITORY_URL: 'URL de repositorio remoto',
  REPOSITORY_URL: 'URL del repositorio',
  REPOSITORY_NAME: 'Nombre del repositorio',
  RESCAN: 'Reescanear',

  RUN: 'ejecutar',
  'Run Pipeline': 'Ejecutar pipeline',
  'Save Artifact': 'Guardar artefacto',
  SCAN_INTERVAL: 'Intervalo de escaneo',
  LOGS_SCANNED_SUCCESSFULLY: 'Escanear registros correctos',
  'Scan repo success': 'Escanear el repositorio correcto',
  REPO_SCAN_TRIGGER: 'Repository Scan Trigger',
  'Scan Repository Logs': 'Escanear logs de repositorio',
  'Scan Repository': 'Escanear repositorio',
  SCHEDULED_BUILD: 'Build programada',
  SCM: 'SCM',
  SCRIPT_PATH: 'Ruta del script',
  WEBHOOK_PUSH: 'Webhook Push',
  secretName: 'secretName',
  secretNamespace: 'secretNamespace',
  SELECT_A_PIPELINE: 'selecciona una pipeline',
  SELECT_CODE_REPOSITORY: 'Seleccionar repositorio de código',
  SELECT_THIS_REPOSITORY: 'Selecciona este repositorio',
  Sender: 'Remitente',
  sh: 'sh',
  'Shell commands can be executed in the container':
    'Los comandos de shell se pueden ejecutar en el contenedor',
  'Show Advanced Settings': 'Mostrar configuración avanzada',
  'Show Logs': 'Mostrar logs',
  'Show only the last 10': 'Mostrar solo los últimos 10',
  'show yaml editor': 'muestre el editor de yaml',
  SINGLE_SVN: 'Svn único',
  SVN: 'SVN',
  Skipped: 'Omitido',
  'sonar is the default config name.':
    'sonar es el nombre de configuración predeterminado.',
  "Sorry, you don't have the permission to do this.":
    'Lo sentimos, no tienes permiso para hacer esto.',
  'Specify a container to add nested tasks to execute inside the container':
    'Especifique un contenedor para agregar tareas anidadas para ejecutar dentro del contenedor',
  SCRIPT_PATH_DESC:
    'Especifique la ubicación del archivo Jenkinsfile en el repositorio de código fuente',
  'Start the follow-up task after the inspection':
    'Inicie la tarea de seguimiento después de la inspección.',
  'Started By': 'Empezado por',
  'Stop Job Successfully, Status updated later':
    'Parado de ejecución satisfactorio, se actualizará el estado después',
  SUB_HEALTHY: 'Sub-healthy',
  Subject: 'Tema',
  submitter: 'remitente',
  submitterParameter: 'submitterParameter',
  'Task failed, not operational': 'Tarea fallida, no operativa',
  TaskStatus: 'TaskStatus',
  'Test Result': 'Resultado de la prueba',
  'Text Variable': 'Variable de texto',
  'The conditions required to implement the current phase (optional).':
    'Las condiciones requeridas para implementar la fase actual (opcional).',
  KUBE_CONTENT_TIP:
    'El contenido predeterminado es el kubeconfig del usuario actual.',
  'The environment variable entered before running the pipeline is match the current value.':
    'La variable de entorno ingresada antes de ejecutar la pipeline coincide con el valor actual.',
  'The label on which to run the Pipeline or individual stage':
    'La etiqueta en la que se ejecuta la pipeline o la fase individual',
  PIPELINE_NAME_DESC:
    'El nombre de la pipeline. Las pipelines en el mismo proyecto deben tener nombres diferentes.',
  'This name has been used.': 'Este nombre ha sido usado.',
  'Time Used': 'Tiempo utilizado',
  Timeout: 'Se acabó el tiempo',
  TIMEOUT_VALUE: 'Se acabó el tiempo: {value}',
  timeout: 'se acabó el tiempo',
  'Timeout after no activity in logs for this block':
    'Tiempo de espera agotado tras inactividad en los logs deregistro de este bloque',
  timer: 'temporizador',
  TOKEN_PASSWORD: 'Token/Contraseña',
  TRIGGER_REMOTE_BUILD:
    'Ejecutar una build remota (por ejemplo, usando un script)',
  TRUSTED_USER: 'Usuario de confianza',
  Unnamed: 'Sin nombre',
  'url is invalid': 'la url no es válida',
  'Use the following URL to remotely triggerworkbench the build':
    'Utilice la siguiente URL para activar remotamente el triggerworkbench en el build',
  'User types that can trigger builds':
    'Tipos de usuarios que pueden desencadenar compilaciones',
  'username or group name, multiple values ​​used, separated':
    'nombre de usuario o nombre de grupo, múltiples valores utilizados, separados',
  'Username Variable': 'Variable Username',
  usernameVariable: 'usernameVariable',
  'Wait for interactive input': 'Espere entrada interactiva',
  waitForQualityGate: 'waitForQualityGate',
  HEALTH: 'Health',
  Webhook: 'Webhook',
  WHEN_CREATE_PIPELINE: 'Cuando crear pipeline',
  WHEN_DELETE_PIPELINE: 'Cuando eliminar pipeline',
  ENABLE_SHALLOW_CLONE: 'Enable shallow clone',
  withCredentials: 'con credenciales',
  withSonarQubeEnv: 'withSonarQubeEnv',
  'Wrong Token': 'Token incorrecto',
  'You can execute shell commands or windows batch commands in the build.':
    'Puedes ejecutar comandos de shell o comandos por lotes de Windows en el build.',
  PIPELINE_DESC: `A pipeline is an extensible set of tools that can be combined
    to achieve continuous integration and continuous delivery.
    You can create and manage pipelines on this page.`,
  username_password: 'Credenciales de cuenta',
  login_Plateform: 'Plataforma de inicio de sesión',
  CREDENTIALS_DESC:
    'La credencial es un objeto que contiene algunos datos confidenciales, como nombre de usuario y contraseña, clave SSH y token. Se utiliza para proporcionar autenticación para el proceso de extraer código empujar / extraer imágenes, ejecutar scripts SSH, etc. cuando se está ejecutando una pipeline.',
  PARAMETERIZED_BUILD_TIP:
    'El proceso de compilación parametrizado le permite pasar uno o más parámetros cuando construye. Por ejemplo: puedes tener una pipeline para publicar software y desea cargar las notas de la versión juntas. Esto se puedes hacer agregando parámetros de texto aquí. Cada parámetro tiene un Nombre y un Valor y el valor del Valor depende del tipo de parámetro. Se puedes acceder a estos valores en la canalización mediante params.Name o Name. Esto significa que cada parámetro definido aquí debe tener un nombre único. Al parametrizar un proyecto, la compilación se reemplaza por una compilación parametrizada que solicita al usuario que introduce un valor para cada parámetro definido. Si eligen no ingresar nada, la compilación continúa con el valor predeterminado para cada parámetro. Si la compilación del proyecto se inicia automáticamente, por ejemplo, mediante un disparador temporizado, se disparará con el valor predeterminado del parámetro.',
  AUTHENTICATION_TOKEN_TIP:
    'Habilite esta opción si necesita activar una compilación accediendo a una URL predefinida. Un uso típico de esta función es activar el script de enlace del sistema de administración del código fuente. Debe proporcionar un token de autorización en forma de cadena para que solo la persona con el token de autorización pueda activar la compilación remota.',
  DISABLE_CONCURRENT_TIP:
    'Esto determinará cuándo se debe descartar el registro de compilación del proyecto. Los registros de compilación incluyen salida de consola, artefactos de archivo y otros metadatos relacionados con una compilación particular. Mantener menos compilaciones ahorra espacio en disco utilizado por Jenkins. Proporcionamos dos condiciones para determinar cuándo se debe descartar la compilación anterior: 1. Número de días para mantener la compilación: la compilación se descartará después de un cierto número de días. 2. Número de compilaciones que se conservarán: si ya hay un cierto número de compilaciones, descarte la compilación más antigua. Estas dos condiciones se aplican a la compilación al mismo tiempo y si se cumple alguna de ellas, la compilación se descartará.',
  DISABLE_CONCURRENT_SCM_TIP:
    'Esto determinará cuándo se debe descartar la rama y todos los registros de compilación debajo de la rama. El registro de compilación incluye los artefactos de archivo de salida de la consola y otros metadatos relacionados con una compilación en particular. Mantener menos compilaciones ahorra espacio en disco utilizado por Jenkins. Proporcionamos dos opciones para determinar cuándo debe descartarse la rama anterior: 1. Número de días para conservar la rama: si la rama alcanza un cierto número de días, la rama se descarta. 2. Número de ramas reservadas: si ya existe un cierto número de ramas, se descarta la rama más antigua. Estas dos opciones pueden funcionar en la sucursal al mismo tiempo. Si se excede alguno de los límites, se eliminarán las ramas que excedan este límite.',
  SCHEDULED_BUILD_TIP:
    'It provides cron-like functionality to run this pipeline regularly.',
  DAYS_TO_KEEP_BRANCHES_DESC:
    'Old branches are discarded after this number of days. The default value is 7.',
  MAXIMUM_NUMBER_OF_BRANCHES_TO_KEEP_DESC:
    'Old branches are discarded when the branch number exceeds the maximum number. The default value is 5.',
  CRON_TIP:
    'Este campo sigue la sintaxis cron (ligeramente diferente). Específicamente, cada línea contiene 5 campos separados por tabulaciones o espacios. minutos: los primeros minutos de una hora (0-59) horas: las primeras horas del día (0-23) los días del mes: los primeros días de un mes (1-31) Mes: el primero pocos días de los primeros días (0-12), los primeros días de la semana (0-12) 0 y 7 son domingos.',
  PIPELINES_BASEINFO_DESC: 'Introduce la información básica de la pipeline.',
  PIPELINE_ADVANCE_SETTINGS_DESC:
    'Configure una política de comportamiento compleja para la pipeline (Opcional).',
  CREDENTIALS_CREATE_DESC: 'Crear credenciales para proyectos DevOps',
  CHECKOUT_DESC:
    'Código de extracción; a menudo se usa para extraer código no git, como svn.',
  PRIVATE_IMAGE_DESC:
    'Para implementar desde un repositorio de imágenes privado, debe crear un repositorio reflejado y luego extraer la imagen.',
  AGENT_TYPE_DESC:
    'La sección del agente especifica dónde se ejecutará toda la canalización o una etapa particular en el entorno de Jenkins, dependiendo de dónde se coloque la parte del agente. Esta parte debe definirse en el nivel superior dentro del bloque de canalización, pero el uso del nivel de etapa es opcional.',
  AUTHENTICATION_TOKEN_DESC:
    'Utilice la siguiente URL para activar la compilación de forma remota: JENKINS_URL / job / JOB_NAME / build? Token = TOKEN_NAME o / buildWithParameters? Token = TOKEN_NAME Puedes elegir agregar & cause = reason para proporcionar el texto que se incluirá en el motivo de compilación del registro.',
  ACTIVITY_EMPTY_TIP: 'La pipeline actual aún no se está ejecutando',
  PIPELINE_NO_CONFIG:
    'El archivo de configuración relevante no se encontró en la pipeline actual',
  NOT_VALID_JENKINS_FILE:
    'El Jenkinsfile actual no es un Jenkinsfile declarativo estándar y no se puedes mostrar gráficamente',
  PIPELINE_CRONJOB_CRON_DESC: `For syntax reference, refer to
    <a href="//jenkins.io/doc/book/pipeline/syntax/#cron-syntax" target="_blank">CRON</a>.`,
  WEBHOOK_PUSH_DESC:
    'Empuje un mensaje a esta URL para activar una reindexación del repositorio.',
  WEBHOOK_DESC: 'Configure webhook notifications by setting a webhook server.',
  TIME_TRIGGER_DESC:
    'Algunos tipos de elementos se volverán a indexar automáticamente cuando reciban un mensaje push externo. Sin embargo, en algunos casos, las notificaciones de mensajes pueden fallar. Esta opción verificará si el índice se ha ejecutado dentro del intervalo de tiempo especificado y, si no, activará el índice.',
  KUBERNETES_DEPLOY_DESC:
    'Implemente recursos en un clúster de Kubernetes. En un entorno de integración continua o despliegue contínuo, solo aquellos recursos que necesitan actualizarse regularmente deben colocarse en el paso de despliegue. Por lo tanto, este paso se utiliza principalmente para procesar el despliegue de dichos recursos.',
  KUBERNETES_DEPLOY_DESC_MORE: `<br />
    <label>Este paso tiene las siguientes características principales:</label>
    <li> Distribución sin kubectl </li>
    <li> Sustitución variable en Jenkinsfile, es posible la implementación dinámica. </li>
    <li> Soporte para dibujar imágenes acoplables desde repositorios de imágenes privadas </li>
    <label> Actualmente, este paso admite los siguientes recursos:</label>
    <br />
    <li> Configuración </li>
    <li> Llave </li>
    <li> Desplegar </li>
    <li> Dave Process Set </li>
    <li> Enrutamiento de aplicaciones </li>
    <li> Namespace </li>
    <li> Tarea </li>
    <li> Servicio </li>
    <li> Conjunto de réplica </li>
    <li> Controlador de replicación
    (las actualizaciones continuas no son compatibles, use la implementación si desea usar actualizaciones continuas)
    </li>`,
  OPTIONS_PR_PARAMS_1:
    'Versión del código fuente de PR fusionada con la rama de destino',
  OPTIONS_PR_PARAMS_2: 'Versión del código fuente del propio RP',
  OPTIONS_PR_PARAMS_3:
    'Se crean dos pipelines cuando se descubre PR. Una canalización utiliza la versión del código fuente de PR en sí Una versión canalizada del código fuente se fusionó con la rama de destino utilizando PR',
  ADD_NEW_CREDENTIAL_DESC:
    'La obtención del código del repositorio puedes requerir credenciales. Selecciona una credencial existente o agregue una nueva.',
  PIPELINE_PREPAIR_DESC:
    'El ambiente se está preparando. Habrá una pantalla gráfica más tarde.',
  PARAMS_DESC:
    'Los siguientes parámetros se generan en función de la configuración de la pipeline o la sección de parámetros del archivo Jenkins, que se ingresan de acuerdo con los requisitos operativos.',
  EDIT_CREDENTIAL_DESC:
    'El siguiente formulario no mostrará la información de credenciales original. Volver a ingresarlo lo sobrescribirá.',
  pipeline_conditions: 'Condiciones',
  PARAMS_STRING: 'Cuerda',
  PARAMS_TEXT: 'Texto',
  PARAMS_BOOLEAN: 'Booleano',
  PARAMS_CHOICE: 'Elección',
  PARAMS_PASSWORD: 'Contraseña',
  CODE_SMELL: 'Olor de código',
  BUG: 'Insecto',
  VULNERABILITY: 'Vulnerabilidad',
  SECURITY_HOTSPOT: 'Punto de acceso de seguridad',
  REG_FILTER_TITLE: 'Filter by name (with regular expression)',
  REG_FILTER_DESC:
    'Habilite las expresiones regulares, ignorando los nombres que no coinciden con la expresión regular proporcionada (incluidas las ramas y PR, etc.)',
  waitForQualityGate_desc:
    'Los estándares de control de calidad del código se derivan de la puerta de calidad de SonarQube. Si necesita personalizar los estándares, vaya a la configuración de SonarQube.',
  PIPELINE_CREATE_DESC:
    'La ejecución de la tarea de Pipeline comenzará después de que se complete la inicialización.',
  REVIEW_DESC:
    'Cuando la pipeline se ejecute aquí, esta tarea se suspenderá y podrás optar por continuar o finalizar después de la revisión.',
  INPUT_DESC:
    'Cuando la canalización se ejecuta aquí, la tarea se suspenderá, y el creador y @somebody pueden elegir continuar o finalizar la canalización.',
  INPUT_MESSAGE_DESC:
    'Este mensaje se mostrará en el estado de ejecución de la canalización.',
  withSonarQubeEnv_DESC:
    'Localice rápidamente errores potenciales u obvios en su código',
  waitForQualityGate_DESC:
    'Ejecutado después de realizar el análisis de código',
  script_DESC: 'Ejecutar script maravilloso',
  PIPELINE_QUEUED_TITLE: 'La pipeline se inicializará pronto',
  PIPELINE_QUEUED_DESC:
    'Debe esperar a que el agente se inicie y ejecute la canalización (tenga en cuenta que si el agente no se ha iniciado durante mucho tiempo, verifique la configuración del agente y los recursos del clúster).',
  pipeline_owner:
    'El propietario del proyecto DevOps, con la máxima autorización del proyecto, puedes realizar todas las operaciones.',
  pipeline_maintainer:
    'El responsable del proyecto DevOps puedes realizar credenciales y configuración de canalización en el proyecto DevOps',
  pipeline_developer:
    'El desarrollador del proyecto DevOps puedes activar y ver la pipeline',
  pipeline_reporter:
    'El observador del proyecto DevOps solo puedes ver los recursos del proyecto',
  LoadPrevData_Desc:
    'Se detectó que esta pipeline no se editó correctamente la última vez. ¿Se cargan los últimos datos para continuar editando?',
  PATTERN_PIPELINE_NAME_VALID_NAME_TIP:
    'Nombre no válido (admite letras mayúsculas y minúsculas, números, "_" y "-")',
  WRONG_GITHUB_TOKEN_DESC: `Token incorrecto
    <a
      class="float-right"
      href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
      target="_blank"
    >
      Get Token
    </a>`,
  GET_GITHUB_TOKEN_DESC: `Para acceder a GitHub
    <a
      class="float-right"
      href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
      target="_blank"
    >
      Get Token
    </a>`,
  bitbucket_server_ACCESSTOKEN_PLACEHOLDER:
    'Introduce la información de su cuenta de Bitbucket.',
  github_ACCESSTOKEN_PLACEHOLDER: 'Introduce su token de acceso de GitHub.',
  PIPELINES_FOOTER_SEE_MORE:
    'Vaya a la página de detalles de la sucursal para ver más.',
  CRON_DESC:
    'Habría corrido por última vez en {lastTime}; se ejecutará a las {nextTime}',
  JENKINS_LINS_ERROR: 'tiene un error de sintaxis en la línea {line}.',
  WHEN_DELETE_PIPELINE_DESC:
    'Cuando se elimina una pipeline, las tareas en la pipeline especificada se activan automáticamente.',
  WHEN_CREATE_PIPELINE_DESC:
    'Cuando se crea una nueva pipeline, las tareas en la pipeline especificada se activan automáticamente.',
  'Started By {name}': 'Comenzado por {name}',
  CREDENTIAL_ID_TIP: 'El ID de credencial ya existe',
  'Invalid credential ID': 'Invalid credential ID',
  CI: 'Continuous Integration (CI)',
  CI_DESC:
    'Continuous integration (CI) is the process of automatically detecting, pulling, building, and (in most cases) unit testing after source code changes.',
  CICD: 'Continuous Integration & Delivery (CI/CD)',
  CICD_DESC:
    "Continuous deployment (CD) refers to the idea of automatically providing the release version in the continuous delivery pipeline to end users. According to the user's installation method, automatic deployment in the cloud environment, app upgrades (such as apps on mobile phones), website updates, or only the list of available versions.",
  CUSTOM_PIPELIEN: 'Custom Pipeline',
  CUSTOM_PIPELIEN_DESC:
    'You can select the tasks you need to customize the work content of the pipeline.',
  COPY_PIPELINE: 'Copiar pipeline',
  'Batch Run Start': 'Batch Run Start',
  'Batch Run Success': 'Batch Run Completed',
  'Batch Run Fail': 'Batch Run Failed',
  'Run Start': 'Start Running',
  GITLAB_SERVER: 'GitLab Server',
  GITLAB_PROJECT_OWNER: 'GitLab Project Owner',
  CREATE_PIPELINE_DESC: 'Build, test and deploy with Pipelines',
  'Choose a Pipeline Template': 'Choose a Pipeline Template',
  BATCH_RUN_DESC: 'Multi-branch pipelines cannot run in a batch.',
  'Sync Status': 'Sync Status',

  // Pipeline List Page
  PULL_REQUEST_PL: 'Pull Requests',
  HEALTHY: 'Healthy',

  // Pipeline Creation Page
  DEVOPS_PROJECT_DESC:
    'DevOps projects are used to group resources and control the resource management permissions of different users.',
  CODE_REPOSITORY_OPTIONAL: 'Repositorio de Código (Opcional)',
  TOKEN: 'Token',
  OPTIONS: 'Options',
}
